### ISSUE TITLE
Mysterious output with webpack 4 and style related loaders

### ISSUE THREAD

**Issue by hieuhlc** [stephencookdev/speed-measure-webpack-plugin#45]
I'm using latest versions of everything: webpack, loaders & speed-measure-webpack-plugin.
I run webpack build with production config and got this result

![41343887-f6e55208-6f29-11e8-8937-f181d445a18f](https://user-images.githubusercontent.com/4828178/41495145-934db082-714a-11e8-8535-84702413837a.png)

I don't understand why and what should I do to optimize (prevent duplicate???)

**Comment by stephencookdev** [comment]
Hey @hieuhlc - yes, this is expected because of the way that the Extract plugins work.

Let me deep-dive a little bit to get a more in-depth answer before giving you the exact reasons why (and if there's anything you can do to speed it up, I think the answer is "not really no, other than disabling the extract-plugin in development mode" off the top of my head, though)

Where would you search for an answer like this, though? I'm not 100% sure where to put information like this, and I'm worried about polluting the terminal output too much

**Comment by hieuhlc** [comment]
Hi @stephencookdev , thanks for your answer. How webpack plugins work is still mystery to me but at least now I know I didn't have wrong configuration.
The reason why there were many information on the terminal is because I used verbose mode. Although it would be great if I can understand the meaning of _median_, _mean_ and _s.d._

**Comment by stephencookdev** [comment]
I've raised https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/51 to hopefully address the root of this confusion
