### ISSUE TITLE
output info of loader about less appear multiple times

### ISSUE THREAD

**Issue by YanYuanFE** [stephencookdev/speed-measure-webpack-plugin#47]
![image](https://user-images.githubusercontent.com/17774285/43820054-a63def26-9b17-11e8-89ad-22a3f9cd59f1.png)

why appear multiple times ？

How to optimize？

my webpack config
https://github.com/YanYuanFE/react-start-app/blob/master/config/webpack.config.dev.js

**Comment by ethikz** [comment]
I'm facing the same issue, except with other loaders

**Comment by anton164** [comment]
I believe this is because you have two entries in your webpack config that involve the `less-loader`:
https://github.com/YanYuanFE/react-start-app/blob/master/config/webpack.config.dev.js#L50
https://github.com/YanYuanFE/react-start-app/blob/master/config/webpack.config.dev.js#L78

Can't you merge them into one, and use an array for `include: /node_modules/`?

From my config:
```
        include: [
          appModulesPath,
          lessPath,
          bowerComponentsPath,
          path.resolve(__dirname, 'node_modules')
        ],
```

**Comment by stephencookdev** [comment]
This is the same as https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/45

This is expected output, but it is just inherently confusing. The way webpack runs, the different loaders run in different configurations, and without setting SMP's `granularLoaderData` option, what SMP outputs is also, unfortunately, quite confusing!

I've raised https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/51 to hopefully address the confusion
